[2024-05-04T13:00:32.125+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T13:00:32.144+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: for_project.upload_clean_to_gcs scheduled__2024-05-04T12:00:00+00:00 [queued]>
[2024-05-04T13:00:32.153+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: for_project.upload_clean_to_gcs scheduled__2024-05-04T12:00:00+00:00 [queued]>
[2024-05-04T13:00:32.153+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-04T13:00:32.177+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_clean_to_gcs> on 2024-05-04 12:00:00+00:00
[2024-05-04T13:00:32.190+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=101553) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T13:00:32.191+0000] {standard_task_runner.py:63} INFO - Started process 101572 to run task
[2024-05-04T13:00:32.195+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'for_project', 'upload_clean_to_gcs', 'scheduled__2024-05-04T12:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_project.py', '--cfg-path', '/tmp/tmp8g645q3g']
[2024-05-04T13:00:32.196+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask upload_clean_to_gcs
[2024-05-04T13:00:32.293+0000] {task_command.py:426} INFO - Running <TaskInstance: for_project.upload_clean_to_gcs scheduled__2024-05-04T12:00:00+00:00 [running]> on host 5bc5768c5236
[2024-05-04T13:00:32.431+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='for_project' AIRFLOW_CTX_TASK_ID='upload_clean_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T12:00:00+00:00'
[2024-05-04T13:00:32.432+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T13:00:32.443+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-04T13:00:32.449+0000] {base.py:84} INFO - Using connection ID 'project_conn' for task execution.
[2024-05-04T13:00:32.450+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T13:00:32.450+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /opt/***/dags/data/all_data.csv
[2024-05-04T13:00:32.463+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=for_project, task_id=upload_clean_to_gcs, execution_date=20240504T120000, start_date=20240504T130032, end_date=20240504T130032
[2024-05-04T13:00:32.483+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task upload_clean_to_gcs (/opt/***/dags/data/all_data.csv; 101572)
[2024-05-04T13:00:32.497+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T13:00:32.551+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T13:00:32.582+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
