[2024-05-05T06:09:15.242+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T06:09:15.255+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.get_files manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T06:09:15.262+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.get_files manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T06:09:15.262+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T06:09:15.278+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_files> on 2024-05-05 06:09:12.404579+00:00
[2024-05-05T06:09:15.288+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'get_files', 'manual__2024-05-05T06:09:12.404579+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmplzdyiapz']
[2024-05-05T06:09:15.289+0000] {standard_task_runner.py:91} INFO - Job 92: Subtask get_files
[2024-05-05T06:09:15.293+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=61790) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T06:09:15.293+0000] {standard_task_runner.py:63} INFO - Started process 61802 to run task
[2024-05-05T06:09:15.331+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.get_files manual__2024-05-05T06:09:12.404579+00:00 [running]> on host 5bc5768c5236
[2024-05-05T06:09:15.412+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='get_files' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T06:09:12.404579+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T06:09:12.404579+00:00'
[2024-05-05T06:09:15.413+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T06:09:16.915+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1061 InsecureRequestWarning: Unverified HTTPS request is being made to host 'opendata.onde.go.th'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
[2024-05-05T06:09:21.333+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-05T06:09:21.333+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T06:09:21.344+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sample, task_id=get_files, execution_date=20240505T060912, start_date=20240505T060915, end_date=20240505T060921
[2024-05-05T06:09:21.393+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T06:09:21.427+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-05T06:09:21.440+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
