[2024-05-04T14:00:03.263+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T14:00:03.283+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: for_project.get_files scheduled__2024-05-04T13:00:00+00:00 [queued]>
[2024-05-04T14:00:03.293+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: for_project.get_files scheduled__2024-05-04T13:00:00+00:00 [queued]>
[2024-05-04T14:00:03.293+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-04T14:00:03.317+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_files> on 2024-05-04 13:00:00+00:00
[2024-05-04T14:00:03.330+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=133702) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T14:00:03.331+0000] {standard_task_runner.py:63} INFO - Started process 133714 to run task
[2024-05-04T14:00:03.335+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'for_project', 'get_files', 'scheduled__2024-05-04T13:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_project.py', '--cfg-path', '/tmp/tmpbg_a4jn0']
[2024-05-04T14:00:03.336+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask get_files
[2024-05-04T14:00:03.403+0000] {task_command.py:426} INFO - Running <TaskInstance: for_project.get_files scheduled__2024-05-04T13:00:00+00:00 [running]> on host 5bc5768c5236
[2024-05-04T14:00:03.508+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='for_project' AIRFLOW_CTX_TASK_ID='get_files' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T13:00:00+00:00'
[2024-05-04T14:00:03.509+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T14:00:04.566+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1061 InsecureRequestWarning: Unverified HTTPS request is being made to host 'opendata.onde.go.th'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
[2024-05-04T14:00:07.892+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-04T14:00:07.892+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T14:00:07.899+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=for_project, task_id=get_files, execution_date=20240504T130000, start_date=20240504T140003, end_date=20240504T140007
[2024-05-04T14:00:07.937+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-04T14:00:07.968+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-04T14:00:07.979+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
