[2024-05-05T07:46:41.793+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T07:46:41.812+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T07:46:41.819+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T07:46:41.819+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-05-05T07:46:41.847+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_clean_to_gcs> on 2024-05-05 06:09:12.404579+00:00
[2024-05-05T07:46:41.859+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'upload_clean_to_gcs', 'manual__2024-05-05T06:09:12.404579+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpysw0u7h9']
[2024-05-05T07:46:41.860+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask upload_clean_to_gcs
[2024-05-05T07:46:41.876+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4028) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T07:46:41.877+0000] {standard_task_runner.py:63} INFO - Started process 4030 to run task
[2024-05-05T07:46:41.936+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [running]> on host 5bc5768c5236
[2024-05-05T07:46:42.035+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='upload_clean_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T06:09:12.404579+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T06:09:12.404579+00:00'
[2024-05-05T07:46:42.036+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T07:46:42.048+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-05T07:46:42.053+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-05T07:46:42.054+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T07:46:42.054+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /opt/***/dags/data/cleaned/*.csv
[2024-05-05T07:46:42.061+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=upload_clean_to_gcs, execution_date=20240505T060912, start_date=20240505T074641, end_date=20240505T074642
[2024-05-05T07:46:42.075+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task upload_clean_to_gcs (/opt/***/dags/data/cleaned/*.csv; 4030)
[2024-05-05T07:46:42.101+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T07:46:42.119+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T07:46:42.127+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
